#ifndef SENSORS_LAYOUT_FH_H
#define SENSORS_LAYOUT_FH_H

#define PTES_LIST \
    DEF(PTE_1, Wire, MUX_0_INSTANCE, 0, 10) \
    DEF(PTE_2, Wire, MUX_0_INSTANCE, 1, 10) \
    DEF(PTE_3, Wire, MUX_0_INSTANCE, 2, 10) \
    DEF(PTE_4, Wire, MUX_0_INSTANCE, 3, 10) \
    DEF(PTE_5, Wire2, MUX_2_INSTANCE, 0, 10) \
    DEF(PTE_6, Wire2, MUX_2_INSTANCE, 1, 10) \

#endif // SENSORS_LAYOUT_FH_H