#ifndef ACTUATORS_LAYOUT_FH_H
#define ACTUATORS_LAYOUT_FH_H

#define SERVOS_LIST \
    DEF(SERVO_1, 0)  \
    DEF(SERVO_2, 1)  \

#define TOGGLES_LIST \
    DEF(TOGGLE_11,  0,  TOGGLE_NC)  \
    DEF(TOGGLE_12,  1,  TOGGLE_NC)  \
    DEF(TOGGLE_13,  2,  TOGGLE_NC)  \
    DEF(TOGGLE_14,  3,  TOGGLE_NC)  \
    DEF(TOGGLE_15,  4,  TOGGLE_NC)  \
    DEF(TOGGLE_16,  5,  TOGGLE_NC)  \
    DEF(TOGGLE_21,  6,  TOGGLE_NC)  \
    DEF(TOGGLE_22,  7,  TOGGLE_NC)  \
    DEF(TOGGLE_23,  8,  TOGGLE_NC)  \
    DEF(TOGGLE_24,  9,  TOGGLE_NC)  \
    DEF(TOGGLE_25, 10,  TOGGLE_NC)  \
    DEF(TOGGLE_26, 24,  TOGGLE_NC)  \
    DEF(TOGGLE_27, 25,  TOGGLE_NC)  \
    DEF(TOGGLE_28, 28,  TOGGLE_NC)

#endif